language: clojure
lein: lein
jdk:
  - oraclejdk8
script:
  - lein check
  - lein kibit
  - lein eastwood
  - lein test
after_success:
  - lein cloverage -o cov --coveralls
  - curl -F 'json_file=@cov/coveralls.json' https://coveralls.io/api/v1/jobs