sudo: required
language: clojure
lein: lein
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-clojure .
script:
  - docker run -it --rm jeremymiller/life-clojure lein omni
  - docker run -it --rm jeremymiller/life-clojure lein test
after_success:
  - lein cloverage -o cov --coveralls
  - curl -F 'json_file=@cov/coveralls.json' https://coveralls.io/api/v1/jobs
